SELECT
    K.GTIN_SGTIN,
    K.GTIN,
    K.SGTIN,
    DOCUMENT_SUB = COALESCE(
        ADS.MNEMOCODE,
        CH.MNEMOCODE,
        M.MNEMOCODE,
        ADE.MNEMOCODE,
        IO.MNEMOCODE,
        AR2C.MNEMOCODE,
        SVED.DOC_NUM),
    K.ID_KIZ,
    K.ID_KIZ_GLOBAL/*,
    K.ID_ERROR,
    K.ID_PARENT,
    K.ID_CONTRACTOR_GLOBAL,
    K.BARCODE,
    K.TNVED4,
    K.BATCH,
    K.BEST_BEFORE,
    K.DATE_TO,
    K.IS_SSCC,
    K.QUANTITY,
    K.IS_MDLP,
    K.ON_HOLD,
    K.[STATE],
    K.ID_TABLE_SUB,
    K.ID_DOCUMENT_SUB,
    K.ID_DOCUMENT_ITEM_SUB,
    K.INSERTED,
    K.UPDATED,
    K.DELETED,
    K.TS,
    L.ID_LOT_GLOBAL,
    L.ID_DOCUMENT,
    L.ID_DOCUMENT_ITEM,
    L.ID_DOCUMENT_ITEM_ADD,
    STATE_NAME = CASE K.[STATE]
	    WHEN 'STOP' THEN 'Выведен из оборота'
        WHEN 'HOLD' THEN 'На остатках'
        WHEN 'PROC' THEN 'На остатках'
        WHEN 'PART' THEN 'Частично выбыл'
        WHEN 'EXIT' THEN 'Выбыл'
        ELSE 'В обработке' END,
    STATE_CODE = CASE K.[STATE]
	    WHEN 'STOP' THEN '4'
        WHEN 'HOLD' THEN '1'
        WHEN 'PROC' THEN '1'
        WHEN 'PART' THEN '3'
        WHEN 'EXIT' THEN '2'
        ELSE '0' END*/
FROM KIZ K(NOLOCK)
    INNER JOIN KIZ_2_DOCUMENT_ITEM KDI(NOLOCK) ON KDI.ID_KIZ_GLOBAL = K.ID_KIZ_GLOBAL
    INNER JOIN LOT L(NOLOCK) ON L.ID_DOCUMENT_ITEM_ADD = KDI.ID_DOCUMENT_ITEM_ADD
	INNER JOIN SCALING_RATIO SR(NOLOCK) ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO AND SR.NUMERATOR = ISNULL(K.QUANTITY, 1)
    LEFT JOIN ACT_DISASSEMBLING ADS(NOLOCK) ON ADS.ID_ACT_DISASSEMBLING_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 6
    LEFT JOIN CHEQUE CH(NOLOCK) ON CH.ID_CHEQUE_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 7
    LEFT JOIN MOVEMENT M(NOLOCK) ON M.ID_MOVEMENT_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 8
    LEFT JOIN ACT_DEDUCTION ADE(NOLOCK) ON ADE.ID_ACT_DEDUCTION_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 20
    LEFT JOIN INVOICE_OUT IO(NOLOCK) ON IO.ID_INVOICE_OUT_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 21
    LEFT JOIN INTERFIRM_MOVING IM(NOLOCK) ON IM.ID_INTERFIRM_MOVING_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 37
    LEFT JOIN ACT_RETURN_TO_CONTRACTOR AR2C(NOLOCK) ON AR2C.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 3
    LEFT JOIN INVENTORY_SVED SVED(NOLOCK) ON SVED.ID_INVENTORY_GLOBAL = K.ID_DOCUMENT_SUB AND K.ID_TABLE_SUB = 24
where CH.MNEMOCODE is not null
and  K.[STATE] = 'EXIT'